### ISSUE TITLE
New signature mechanism does no longer rely on a secret nor on pinned keys

### ISSUE THREAD

**Issue by kwin** [AdobeDocs/adobe-io-events#23]
Issue in /src/pages/guides/index.md
The new verification mechanism from https://www.adobe.io/events/docs/guides/#security-considerations leveraging private/public keys and the client id does no longer leverage any confidential information like client secret. The client id in general is not confidential and might easily leak. That allows malicious attackers to send forged requests, as each request can use an arbitrary public/private key pair as there is no key pinning outlined in the documentation. Can you please clarify how to prevent such attacks?

**Comment by abhupadh** [comment]
Hi Konrad, thanks for going through our documentation and raising your concern. Apologies for not responding earlier. We have got your concern and are actively working on resolving it. You should be getting an update soon. Thanks again!

**Comment by abhupadh** [comment]
Hi Konrad, we understood that we need to strengthen our new signature mechanism and to achieve that we are doing the below -

- In our current implementation, all the events flowing through our pipeline are being signed with a fixed public/private key pair generated by us. We missed clarifying this in our documentation and will do so. 
- The public keys provided via the request headers will be served from our fixed adobe domain i.e. **adobeioevents.com**, so that one can use their own arbitrary private/public keys pairs. The request header will contain only the relative path of the public key and consumer is expected to fetch the key with url of our adobe domain and the key relative path. This will be a minor enhancement to our implementation and will be reflected in our documentation as well. 

Let us know if that clarifies your concern. 

Thanks!
